### ISSUE TITLE
Question:  Where is the airflow.cfg file located

### ISSUE THREAD

**Issue by youngsoul** [justinwagg/docker-airflow-tutorial#2]
Hi - just curious if you might know where in the docker container I could locate the airflow.cfg so I could change some of the configuration.

My understanding is it should be located at: AIRFLOW_HOME which should be /app/airflow.

However when I run the docker container in interactive mode like:
docker run -it --entrypoint /bin/bash -v /home/pi/airflow/dags:/app/airflow/dags --name airflow -p 8080:8080 airflow:0.1.2

the only element in /app/airflow is the dags directory.

I do see the configuration file in the Webserver - just not sure where to locate and change it.

Thanks for any help you might be able to provide.

**Comment by justinwagg** [comment]
Hey @youngsoul thanks for the question!

When you run 

```bash
docker run -it --entrypoint /bin/bash \
    -v /home/pi/airflow/dags:/app/airflow/dags \
    --name airflow \
    -p 8080:8080 airflow:0.1.2
```

Airflow won't have initialized yet, `entrypoint.sh` hasn't yet been executed. So the only thing in `/app/airflow` will be `dags`, from the volume mount.

As soon as you run `airflow db init` though, you'll see the file at `/app/airflow/airflow.cfg`. 

For example:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/9845115/108947899-667de800-762f-11eb-9ed1-34006aaf23d1.png">

If you want to add your own configuration you could create one in the root of the project and add a `COPY` command to the Dockerfile like

```bash
COPY ./airflow.cfg ${AIRFLOW_HOME}/airflow.cfg
```

That will copy your local version into AIRFLOW_HOME, and Airflow will use that. An easy way to test it is to copy the default config from the UI, create `airflow.cfg` locally from that, and add a comment to the top of the file: 

<img width="488" alt="image" src="https://user-images.githubusercontent.com/9845115/108948293-3b47c880-7630-11eb-8c09-36d14273fbe5.png">

Hope it helps!

**Comment by youngsoul** [comment]
Brilliant! - thank you very much.  This makes total sense.
